from __future__ import unicode_literals

from django.db import models

# Create your models here.
class CustomerReport(models.Model):
	customer_id = models.CharField(max_length=30)
	customer_name = models.CharField(max_length=120)
	commodity = models.CharField(max_length=30)
	first_read_date = models.CharField(max_length=30)
	first_read_device = models.CharField(max_length=30)
	active_meters_count = models.CharField(max_length=30)
	inactive_meters_count = models.CharField(max_length=30)
	orphaned_meters_count = models.CharField(max_length=30)

class MasterData(models.Model):
	utility = models.CharField(max_length=120)
	customer_id = models.CharField(max_length=120)
	status_for_reporting = models.CharField(max_length=120)
	integrator = models.CharField(max_length=120)
	build_product = models.CharField(max_length=120)
	ps_engagement = models.CharField(max_length=120)
	transformer = models.CharField(max_length=120)
	energy_insight = models.CharField(max_length=120)
	voltage_insight = models.CharField(max_length=120)
	unbilled_energy = models.CharField(max_length=120)
	oms = models.CharField(max_length=120)
	sma = models.CharField(max_length=120)
	additional_notes = models.CharField(max_length=2400)
	rni_new_or_migration = models.CharField(max_length=120)
	time_zone = models.CharField(max_length=120)
	w_end_points = models.CharField(max_length=120)
	e_end_points = models.CharField(max_length=120)
	g_end_points = models.CharField(max_length=120)
	jira_ticket = models.CharField(max_length=120)
	region = models.CharField(max_length=120)
	project_code = models.CharField(max_length=120)
	sensus_order = models.CharField(max_length=120)
	salesforce_case = models.CharField(max_length=120)
	order_date = models.CharField(max_length=120)
	sa_handed_to_integrator = models.CharField(max_length=120)
	sent_for_invoicing_on = models.CharField(max_length=120)
	annual_fee_trigger_date = models.CharField(max_length=120)
	one_time_setup_fee = models.CharField(max_length=120)
	year1_annual_fee = models.CharField(max_length=120)
	year2_annual_fee = models.CharField(max_length=120)
	year3_annual_fee = models.CharField(max_length=120)
	year4_annual_fee = models.CharField(max_length=120)
	year5_annual_fee = models.CharField(max_length=120)
	total_end_points = models.CharField(max_length=120)
	var = models.CharField(max_length=120)
	point_of_contact = models.CharField(max_length=120)
	point_of_contact_emails = models.CharField(max_length=120)
	salesperson = models.CharField(max_length=120)
	name_of_billing_vendor = models.CharField(max_length=120)
	training_fee = models.CharField(max_length=120)
	training_complete = models.CharField(max_length=120)
	time_order_to_hand_over = models.CharField(max_length=120)
	time_handover_to_invoice = models.CharField(max_length=120)
	time_order_to_invoice = models.CharField(max_length=120)
	time_since_order = models.CharField(max_length=120)
	column29 = models.CharField(max_length=120)
	column30 = models.CharField(max_length=120)
	column31 = models.CharField(max_length=120)
	column40 = models.CharField(max_length=120)
	timezone = models.CharField(max_length=120)
	poc_email = models.CharField(max_length=120)
	billing_vendor = models.CharField(max_length=120)
	sa_handed_over_to_integrator_date = models.CharField(max_length=120)
	column32 = models.CharField(max_length=120)
	column37 = models.CharField(max_length=120)
	column38 = models.CharField(max_length=120)
	column39 = models.CharField(max_length=120)
	portal_only = models.CharField(max_length=120)
	migration_type = models.CharField(max_length=120)

class PortalUtility(models.Model):
	customer_id = models.CharField(max_length=50)
	customer_name = models.CharField(max_length=1000)
	portal_users_count = models.CharField(max_length=100)
	water = models.CharField(max_length=10)
	gas = models.CharField(max_length=10)
	electric = models.CharField(max_length=10)
	alerts = models.CharField(max_length=10)
	bill = models.CharField(max_length=10)
	dashboard_menu = models.CharField(max_length=10)
	goal = models.CharField(max_length=10)
	goals =models.CharField(max_length=10)
	goal_menu = models.CharField(max_length=10)
	google_maps = models.CharField(max_length=10)
	mactivity = models.CharField(max_length=10)
	meters = models.CharField(max_length=10)
	meters_menu = models.CharField(max_length=10)
	notifications = models.CharField(max_length=10)
	outages = models.CharField(max_length=10)
	outages_menu = models.CharField(max_length=10)
	outdoors = models.CharField(max_length=10)
	peers = models.CharField(max_length=10)
	recipients = models.CharField(max_length=10)
	recipients_menu = models.CharField(max_length=10)
	terms = models.CharField(max_length=10)
	treshold = models.CharField(max_length=10)
	tresholds = models.CharField(max_length=10)
	treshhold_menu = models.CharField(max_length=10)
	units = models.CharField(max_length=10)
	units_menu = models.CharField(max_length=10)
	usage = models.CharField(max_length=10)
	usage_detail = models.CharField(max_length=10)
	usage_forecast_menu = models.CharField(max_length=10)
	user = models.CharField(max_length=10)
	user_menu = models.CharField(max_length=10)
	usg_disclaimer = models.CharField(max_length=10)
	other_groups = models.CharField(max_length=10)
	
