# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('commodity', models.CharField(max_length=30)),
                ('first_read_date', models.CharField(max_length=30)),
                ('first_read_device', models.CharField(max_length=30)),
                ('active_meters_count', models.CharField(max_length=30)),
                ('inactive_meters_count', models.CharField(max_length=30)),
                ('orphaned_meters_count', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=30)),
                ('status_for_reporting', models.CharField(max_length=30)),
                ('integrator', models.CharField(max_length=30)),
                ('build_product', models.CharField(max_length=30)),
                ('ps_engagement', models.CharField(max_length=30)),
                ('transformer', models.CharField(max_length=30)),
                ('energy_insight', models.CharField(max_length=30)),
                ('voltage_insight', models.CharField(max_length=30)),
                ('unbilled_energy', models.CharField(max_length=30)),
                ('oms', models.CharField(max_length=30)),
                ('sma', models.CharField(max_length=30)),
                ('additional_notes', models.CharField(max_length=30)),
                ('rni_new_or_migration', models.CharField(max_length=30)),
                ('time_zone', models.CharField(max_length=30)),
                ('w_end_points', models.CharField(max_length=30)),
                ('e_end_points', models.CharField(max_length=30)),
                ('g_end_points', models.CharField(max_length=30)),
                ('jira_ticket', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('project_code', models.CharField(max_length=30)),
                ('sensus_order', models.CharField(max_length=30)),
                ('salesforce_case', models.CharField(max_length=30)),
                ('order_date', models.CharField(max_length=30)),
                ('sa_handed_to_integrator', models.CharField(max_length=30)),
                ('sent_for_invoicing_on', models.CharField(max_length=30)),
                ('annual_fee_trigger_date', models.CharField(max_length=30)),
                ('one_time_setup_fee', models.CharField(max_length=30)),
                ('year1_annual_fee', models.CharField(max_length=30)),
                ('year2_annual_fee', models.CharField(max_length=30)),
                ('year3_annual_fee', models.CharField(max_length=30)),
                ('year4_annual_fee', models.CharField(max_length=30)),
                ('year5_annual_fee', models.CharField(max_length=30)),
                ('total_end_points', models.CharField(max_length=30)),
                ('var', models.CharField(max_length=30)),
                ('point_of_contact', models.CharField(max_length=30)),
                ('point_of_contact_emails', models.CharField(max_length=30)),
                ('salesperson', models.CharField(max_length=30)),
                ('name_of_billing_vendor', models.CharField(max_length=30)),
                ('training_fee', models.CharField(max_length=30)),
                ('training_complete', models.CharField(max_length=30)),
                ('time_order_to_hand_over', models.CharField(max_length=30)),
                ('time_handover_to_invoice', models.CharField(max_length=30)),
                ('time_order_to_invoice', models.CharField(max_length=30)),
                ('time_since_order', models.CharField(max_length=30)),
                ('column29', models.CharField(max_length=30)),
                ('column30', models.CharField(max_length=30)),
                ('column31', models.CharField(max_length=30)),
                ('column40', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
                ('poc_email', models.CharField(max_length=30)),
                ('billing_vendor', models.CharField(max_length=30)),
                ('sa_handed_over_to_integrator_date', models.CharField(max_length=30)),
                ('column32', models.CharField(max_length=30)),
                ('column37', models.CharField(max_length=30)),
                ('column38', models.CharField(max_length=30)),
                ('column39', models.CharField(max_length=30)),
                ('portal_only', models.CharField(max_length=30)),
                ('migration_type', models.CharField(max_length=30)),
            ],
        ),
    ]
