# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreport',
            name='customer_name',
            field=models.CharField(max_length=60),
        ),
    ]
