# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20191002_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='additional_notes',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='build_product',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='customer_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='e_end_points',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='energy_insight',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='g_end_points',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='integrator',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='jira_ticket',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='oms',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='project_code',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='ps_engagement',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='region',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='rni_new_or_migration',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='sensus_order',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='sma',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='time_zone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='transformer',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='unbilled_energy',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='voltage_insight',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='w_end_points',
            field=models.CharField(max_length=60),
        ),
    ]
