# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20191002_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='additional_notes',
            field=models.CharField(max_length=2400),
        ),
    ]
