# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20191002_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=1000)),
                ('portal_users_count', models.CharField(max_length=100)),
                ('water', models.CharField(max_length=10)),
                ('gas', models.CharField(max_length=10)),
                ('electric', models.CharField(max_length=10)),
                ('alerts', models.CharField(max_length=10)),
                ('bill', models.CharField(max_length=10)),
                ('dashboard_menu', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
                ('goals', models.CharField(max_length=10)),
                ('goal_menu', models.CharField(max_length=10)),
                ('google_maps', models.CharField(max_length=10)),
                ('mactivity', models.CharField(max_length=10)),
                ('meters', models.CharField(max_length=10)),
                ('meters_menu', models.CharField(max_length=10)),
                ('notifications', models.CharField(max_length=10)),
                ('outages', models.CharField(max_length=10)),
                ('outages_menu', models.CharField(max_length=10)),
                ('outdoors', models.CharField(max_length=10)),
                ('peers', models.CharField(max_length=10)),
                ('recipients', models.CharField(max_length=10)),
                ('recipients_menu', models.CharField(max_length=10)),
                ('terms', models.CharField(max_length=10)),
                ('treshold', models.CharField(max_length=10)),
                ('tresholds', models.CharField(max_length=10)),
                ('treshhold_menu', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=10)),
                ('units_menu', models.CharField(max_length=10)),
                ('usage', models.CharField(max_length=10)),
                ('usage_detail', models.CharField(max_length=10)),
                ('usage_forecast_menu', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('user_menu', models.CharField(max_length=10)),
                ('usg_disclaimer', models.CharField(max_length=10)),
                ('other_groups', models.CharField(max_length=10)),
            ],
        ),
    ]
