# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_portalutility'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingsBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100)),
                ('salesperson', models.CharField(max_length=100)),
                ('date_entered', models.CharField(max_length=100)),
                ('cust_name_bill_to', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=1000)),
                ('order_number', models.CharField(max_length=100)),
                ('order_line_number', models.CharField(max_length=100)),
                ('total_sales', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('unit_sales_price', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('date_invoiced', models.CharField(max_length=100)),
                ('ship_to_number', models.CharField(max_length=100)),
                ('early_ship', models.CharField(max_length=100)),
                ('promotion_region', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('entered_by', models.CharField(max_length=100)),
                ('item_class', models.CharField(max_length=100)),
                ('date_committed', models.CharField(max_length=100)),
                ('customer_no_bill_to', models.CharField(max_length=100)),
                ('date_requested', models.CharField(max_length=100)),
                ('date_customer_request', models.CharField(max_length=100)),
                ('customer_po', models.CharField(max_length=100)),
                ('warehouse', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('ship_to_state', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('manufacturing_group', models.CharField(max_length=100)),
                ('hold_reason', models.CharField(max_length=100)),
                ('po_number', models.CharField(max_length=100)),
            ],
        ),
    ]
