# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_billingsbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsbacklog',
            name='customer_name_ship_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingsbacklog',
            name='customer_number_bill_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingsbacklog',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingsbacklog',
            name='customer_no_bill_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
