# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20191202_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='project_code',
            field=models.TextField(max_length=1000),
        ),
    ]
